# Generated by Django 5.0 on 2024-01-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
    ]
