# Generated by Django 5.0 on 2024-01-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_app', '0002_remove_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.CharField(max_length=3000),
        ),
    ]
