# Generated by Django 5.0 on 2024-01-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0003_delete_location_district_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
