# Generated by Django 5.0 on 2023-12-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_userlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
