# Generated by Django 5.0 on 2023-12-23 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0002_district_region'),
        ('user_app', '0004_customuser_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='location',
        ),
        migrations.AddField(
            model_name='userlocation',
            name='district',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='location_app.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlocation',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='location_app.region'),
            preserve_default=False,
        ),
    ]
