# Generated by Django 5.0 on 2024-01-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
