# Generated by Django 5.0 on 2024-01-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='seller_category',
        ),
    ]
