# Generated by Django 5.0 on 2023-12-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_order_seller_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='isDeleted',
            new_name='is_delete',
        ),
        migrations.AddField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
