# Generated by Django 5.0 on 2023-12-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_rename_isdeleted_category_is_delete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellercategory',
            old_name='user',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='sellercategory',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
