# Generated by Django 5.0 on 2024-01-29 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0001_initial'),
        ('shop_app', '0006_rename_seller_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='seller_category',
        ),
        migrations.CreateModel(
            name='OrderItemLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_app.district')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.orderitem')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_app.region')),
            ],
        ),
    ]
