# Generated by Django 5.0 on 2024-01-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_rename_user_sellercategory_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_delete',
        ),
    ]
