# Generated by Django 5.0 on 2024-01-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_rename_category_product_seller_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemlocation',
            old_name='order',
            new_name='order_item',
        ),
    ]
