# Generated by Django 5.0 on 2024-01-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coverImage',
            field=models.TextField(),
        ),
    ]
